### PR TITLE
HTML nodes for browsing the design graph

### LINKED ISSUE #2: More readable design graph
Following up on [this blog post][1], the easy way out would be to zoom in a bit and not try to present the whole picture at once.  I expect a nice, interactive, zoom-through-space-style graph-visualization library exists in JavaScript, but I can't find one now.  But turning the graph diagram into a set of linked pages that just show ancestor/descendant graphs for the current node would be fairly straightforward.  For example, the “Collaboration” page would only show the paths passing through that node.  Folks could click on the related entries to see their pages, and gradually walk and internalize the whole graph.

[1]: http://third-bit.com/2016/04/08/trying-to-find-a-form.html

### PR DESCRIPTION
**Pull request by wking**
Using jsTree or some such would make for more compact trees (and we
could drop the current depth cap as long as we don't have cycles in
our graph), but that was more work than I wanted to put into a proof
of concept.

Fixes #2.

### CODE REVIEW

**Comment by gvwilson** [comment]
Sorry, but I don't understand what this does?

**Comment by wking** [comment]
On Thu, Apr 14, 2016 at 01:53:45PM -0700, Greg Wilson wrote:
> Sorry, but I don't understand what this does?

It makes a browsable, zoomed-in view of the design graph.  I've just
pushed the output to [1].  And it looks reasonably helpful to me,
except for nodes that expand too quickly for the currently-hard-coded
recursion depth cap [2].

[1]: http://wking.github.io/swc-long-form/html/m_git.html
[2]: http://wking.github.io/swc-long-form/html/

**Comment by gvwilson** [comment]
So I should be seeing a nested list view like this?

**Comment by wking** [comment]
On Thu, Apr 14, 2016 at 04:43:19PM -0700, Greg Wilson wrote:
> So I should be seeing a nested list view like this?

Like what?  This PR just adds tooling to generate the per-node pages
linked from [1].  That is my “But turning the graph diagram into a set
of linked pages that just show ancestor/descendant graphs for the
current node…” suggestion from [2].  I think it makes the graph easier
to understand (compare [3]) by reducing the amount of information
you're shown at any one time (to just the node you're currently
interested in and its close relatives), but your mileage may vary ;).

Maybe if you unpack your comment a bit more I'll understand it better
;).

[1]: https://github.com/gvwilson/long-form/pull/3#issuecomment-210149698
[2]: https://github.com/gvwilson/long-form/issues/2#issue-147641386
[3]: http://third-bit.com/2016/04/08/trying-to-find-a-form.html

**Comment by gvwilson** [comment]
Exploring other avenues...

**Pull request closed without merging**
